Repository mapbox/mapbox-vision-ios, pull requests merged in 2019-09, with the labels that each got.

#215 Update changelog with 0.8.1 changes
  CHANGELOG.md
Labels: iOS

#214 Release/0.8.1 to master
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: iOS

#206 Move ar to native
  CHANGELOG.md
  Examples/VisionExamples/Constants.swift
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/VisionExamples/Examples/ExternalCameraViewController.swift
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Services/VideoSource/CameraVideoSource.swift
  MapboxVision/Services/VideoSource/VideoSource.swift
  MapboxVision/Services/VideoSource/VideoSourceObserverProxy.swift
  MapboxVision/View/blend.metal
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVisionAR/Models/grid.obj
  MapboxVisionAR/Models/lane.obj
  MapboxVisionAR/Models/nav-arrow.obj
  MapboxVisionAR/Render/ARScene/ARNode/AREntity/ARMaterial/ARLight/ARLight.swift
  MapboxVisionAR/Render/ARScene/ARNode/AREntity/ARMaterial/ARMaterial.swift
  MapboxVisionAR/Render/ARScene/ARNode/ARNode.swift
  MapboxVisionAR/Render/ARScene/ARNode/ARNodeType.swift
  MapboxVisionAR/Render/ARScene/ARNode/NodeGeometry/NodeGeometry.swift
  MapboxVisionAR/Render/ARScene/ARScene.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARCameraNode/ARCameraNode.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARLaneNode/ARLaneNode.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARRootNode/ARRootNode.swift
  MapboxVisionAR/Render/Helpers/ARConstants.swift
  MapboxVisionAR/Render/Helpers/ARMath.swift
  MapboxVisionAR/Render/Helpers/UIColor+Extension.swift
  MapboxVisionAR/Render/Renderer/ARRenderer.swift
  MapboxVisionAR/Render/Renderer/Error/ARMeshError.swift
  MapboxVisionAR/Render/Renderer/Error/ARRendererError.swift
  MapboxVisionAR/Render/Renderer/Shaders/Shaders.metal
  MapboxVisionAR/Render/Renderer/Shaders/Uniform Structures/Uniforms.swift
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAR/VIsionARManager/VisionARManagerDelegate.swift
  MapboxVisionAR/ViewController/LaneVisualParams.swift
  MapboxVisionAR/ViewController/VisionARViewController+ARManager.swift
  MapboxVisionAR/ViewController/VisionARViewController+LaneParams.swift
  MapboxVisionAR/ViewController/VisionARViewController.swift
  MapboxVisionARTests/Info.plist
  MapboxVisionARTests/Render/ARScene/ARNode/NodeStructure/NodeGeometryTests.swift
  MapboxVisionARTests/Render/ARScene/ARSceneTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARCameraNodeTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARLaneNodeTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARRootNodeTests.swift
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
Labels: P0, iOS

#222 Update CHANGELOG.md for 0.9.0
  CHANGELOG.md
Labels: P0, iOS

#226 Update CHANGELOG.md for Vision module
  CHANGELOG.md
Labels: P0, iOS

#228 Release/0.9.0 to dev
  CHANGELOG.md
Labels: P0, iOS

#229 Release/0.9.0 to master
  CHANGELOG.md
  Examples/Cartfile
  Examples/VisionExamples/Constants.swift
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/VisionExamples/Examples/ExternalCameraViewController.swift
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Info.plist
  MapboxVision/Services/VideoSource/CameraVideoSource.swift
  MapboxVision/Services/VideoSource/VideoSource.swift
  MapboxVision/Services/VideoSource/VideoSourceObserverProxy.swift
  MapboxVision/View/blend.metal
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAR/Models/grid.obj
  MapboxVisionAR/Models/lane.obj
  MapboxVisionAR/Models/nav-arrow.obj
  MapboxVisionAR/Render/ARScene/ARNode/AREntity/ARMaterial/ARLight/ARLight.swift
  MapboxVisionAR/Render/ARScene/ARNode/AREntity/ARMaterial/ARMaterial.swift
  MapboxVisionAR/Render/ARScene/ARNode/ARNode.swift
  MapboxVisionAR/Render/ARScene/ARNode/ARNodeType.swift
  MapboxVisionAR/Render/ARScene/ARNode/NodeGeometry/NodeGeometry.swift
  MapboxVisionAR/Render/ARScene/ARScene.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARCameraNode/ARCameraNode.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARLaneNode/ARLaneNode.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARRootNode/ARRootNode.swift
  MapboxVisionAR/Render/Helpers/ARConstants.swift
  MapboxVisionAR/Render/Helpers/ARMath.swift
  MapboxVisionAR/Render/Helpers/UIColor+Extension.swift
  MapboxVisionAR/Render/Renderer/ARRenderer.swift
  MapboxVisionAR/Render/Renderer/Error/ARMeshError.swift
  MapboxVisionAR/Render/Renderer/Error/ARRendererError.swift
  MapboxVisionAR/Render/Renderer/Shaders/Shaders.metal
  MapboxVisionAR/Render/Renderer/Shaders/Uniform Structures/Uniforms.swift
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAR/VIsionARManager/VisionARManagerDelegate.swift
  MapboxVisionAR/ViewController/LaneVisualParams.swift
  MapboxVisionAR/ViewController/VisionARViewController+ARManager.swift
  MapboxVisionAR/ViewController/VisionARViewController+LaneParams.swift
  MapboxVisionAR/ViewController/VisionARViewController.swift
  MapboxVisionARTests/Info.plist
  MapboxVisionARTests/Render/ARScene/ARNode/NodeStructure/NodeGeometryTests.swift
  MapboxVisionARTests/Render/ARScene/ARSceneTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARCameraNodeTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARLaneNodeTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARRootNodeTests.swift
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
  MapboxVisionTests/Info.plist
Labels: P0, iOS

#232 Update version to 0.10.0
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Info.plist
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAR/ViewController/VisionARViewController+LaneParams.swift
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
  MapboxVisionTests/Info.plist
Labels: P0, iOS

#233 Add new ConstructionCone class to DetectionClass.
  CHANGELOG.md
  MapboxVision/View/DetectionsView.swift
Labels: P0, iOS

#225 Improve collecting camera parameters
  CHANGELOG.md
  MapboxVision/Services/VideoSource/CameraVideoSource.swift
Labels: iOS

#235 Add github/stale.yml
  .github/stale.yml
Labels: nostale
