Repository mapbox/mapbox-vision-ios, pull requests merged in 2019-07, with the labels that each got.

#98 Remove MapboxNavigation dependency
  .swiftformat
  .swiftlint.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/Cartfile
  Examples/Cartfile.resolved
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/VisionExamples/Examples/ExternalCameraViewController.swift
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  Examples/scripts/carthage-input.xcfilelist
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Services/MotionManager.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Navigation/ARRoute+DirectionsRoute.swift
  MapboxVisionAR/Navigation/NavigationProvider.swift
  MapboxVisionAR/Render/ARRenderer.swift
  MapboxVisionAR/Render/VisionARViewController.swift
Labels: P0, iOS

#139 Release/0.4.1 to master
  CHANGELOG.md
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: iOS

#140 Release/0.4.1 to dev
  CHANGELOG.md
Labels: iOS

#143 Allow to return optionals from `geoToWorld` and `worldToGeo` methods.
  CHANGELOG.md
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/VisionManagerProtocol.swift
Labels: API Change, P0, iOS, vision core

#131 Fix unit tests on iOS platform
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVisionTests/RecordCoordinatorTests.swift
  MapboxVisionTests/RecordSynchronizerTests.swift
Labels: P0, bug, iOS, invalid, refactoring

#144 Make device's id persistent between sessions
  CHANGELOG.md
  MapboxVision/Services/Constants.swift
  MapboxVision/Services/DeviceInfoProvider.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVisionTests/DeviceInfoProviderTests.swift
Labels: P0, enhancement, iOS

#146 Fix deleting recording path during move
  CHANGELOG.md
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Services/Recording/RecordingPath.swift
  MapboxVisionTests/RecordingPathTests.swift
Labels: P0, iOS

#92 Run models on iPhone Xr/Xs/Xs Max with higher fps
  CHANGELOG.md
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Helpers/DeviceChecker.swift
  MapboxVision/Services/ModelPerformance.swift
  MapboxVisionTests/DeviceCheckerTests.swift
  MapboxVisionTests/Mocks/UIDeviceStubs.swift
Labels: P1, enhancement, iOS

#148 Hotfixes for 0.4.2
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Info.plist
  MapboxVision/Services/Recording/RecordingPath.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
  MapboxVisionTests/RecordingPathTests.swift
Labels: iOS

#149 Release/0.4.2 to master
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Info.plist
  MapboxVision/Services/Recording/RecordingPath.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
  MapboxVisionTests/RecordingPathTests.swift
Labels: iOS

#150 Release/0.4.2 to dev
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxVision.podspec
Labels: iOS

#118 Allow to change parameters for AR lane
  CHANGELOG.md
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVisionAR.xcscheme
  MapboxVisionAR/Render/ARRenderer.swift
  MapboxVisionAR/Render/ARScene.swift
  MapboxVisionAR/Render/ARScene/ARNode/AREntity/ARMaterial/ARLight/ARLight.swift
  MapboxVisionAR/Render/ARScene/ARNode/AREntity/ARMaterial/ARMaterial.swift
  MapboxVisionAR/Render/ARScene/ARNode/ARNode.swift
  MapboxVisionAR/Render/ARScene/ARNode/ARNodeType.swift
  MapboxVisionAR/Render/ARScene/ARNode/NodeGeometry/NodeGeometry.swift
  MapboxVisionAR/Render/ARScene/ARScene.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARCameraNode/ARCameraNode.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARLaneNode/ARLaneNode.swift
  MapboxVisionAR/Render/ARScene/ConcreteNodes/ARRootNode/ARRootNode.swift
  MapboxVisionAR/Render/Helpers/ARConstants.swift
  MapboxVisionAR/Render/Helpers/ARMath.swift
  MapboxVisionAR/Render/Helpers/UIColor+Extension.swift
  MapboxVisionAR/Render/Renderer/ARRenderer.swift
  MapboxVisionAR/Render/Renderer/Error/ARMeshError.swift
  MapboxVisionAR/Render/Renderer/Error/ARRendererError.swift
  MapboxVisionAR/Render/Renderer/Shaders/Shaders.metal
  MapboxVisionAR/Render/Renderer/Shaders/Uniform Structures/Uniforms.swift
  MapboxVisionAR/ViewController/LaneVisualParams.swift
  MapboxVisionAR/ViewController/VisionARViewController.swift
  MapboxVisionARTests/Info.plist
  MapboxVisionARTests/Render/ARScene/ARNode/NodeStructure/NodeGeometryTests.swift
  MapboxVisionARTests/Render/ARScene/ARSceneTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARCameraNodeTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARLaneNodeTests.swift
  MapboxVisionARTests/Render/ARScene/ConcreteNodes/ARRootNodeTests.swift
Labels: P0, enhancement, iOS

#160 Script for documentation generation
  MapboxVision/.jazzy.yaml
  MapboxVision/README.md
  MapboxVisionAR/.jazzy.yaml
  MapboxVisionAR/README.md
  MapboxVisionSafety/.jazzy.yaml
  MapboxVisionSafety/README.md
  scripts/document.sh
Labels: iOS

#161 Set fps using VisionManagerBaseNative
  MapboxVision/VisionManager/BaseVisionManager.swift
Labels: P0, iOS

#163 Update changelog file for release 0.5.0
  CHANGELOG.md
Labels: P0, iOS

#165 Release/0.5.0 to dev
  CHANGELOG.md
  MapboxVision/.jazzy.yaml
  MapboxVision/README.md
  MapboxVisionAR/.jazzy.yaml
  MapboxVisionAR/README.md
  MapboxVisionSafety/.jazzy.yaml
  MapboxVisionSafety/README.md
  scripts/document.sh
Labels: P0, iOS

#155 Update Reachability.swift dependency
  CHANGELOG.md
  MapboxVision/Services/Reachability/Reachability.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
Labels: P2, enhancement, iOS

#153 Fix deployment target for MapboxVision project
  MapboxVision.xcodeproj/project.pbxproj
Labels: P0, bug, enhancement, iOS, invalid

#158 Reuse the existing code that converts world coordinates to render coordinates
  MapboxVisionAR/Render/Renderer/ARRenderer.swift
Labels: P2, enhancement, iOS

#170 Avoid usage deprecated interfaces from Reachability.swift
  MapboxVision/Services/Sync/ManagedSynchronizer.swift
Labels: P0, enhancement, iOS, invalid

#121 Add README.md file
  README.md
Labels: P1, enhancement, iOS

#137 Integrate secret-shield tool for `mapbox-vision-ios`
  .gitignore
  README.md
Labels: P0, enhancement, iOS, operation excellence

#127 Apply linter checks and fix issues
  .swiftformat
  .swiftlint.yml
  Examples/VisionExamples.xcodeproj/project.pbxproj
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Services/Reachability/Reachability.swift
  MapboxVisionAR/Render/Helpers/ARMath.swift
Labels: P1, enhancement, iOS

#136 Fixed destructors without calling destroy
  CHANGELOG.md
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Services/Recording/SessionRecorder.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/SessionRecorderProtocol.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
  MapboxVisionTests/Mocks/MockDataProvider.swift
  MapboxVisionTests/Mocks/MockNative.swift
  MapboxVisionTests/Mocks/MockPlatform.swift
  MapboxVisionTests/Mocks/MockSensors.swift
  MapboxVisionTests/Mocks/MockSessionRecorder.swift
  MapboxVisionTests/Mocks/MockSynchronizable.swift
  MapboxVisionTests/Mocks/MockVideoSource.swift
  MapboxVisionTests/VisionManagerTests.swift
Labels: P0, iOS

#178 Update Examples to Vision 0.5.0
  Examples/Cartfile
  Examples/Cartfile.resolved
  Examples/README.md
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/scripts/carthage-input.xcfilelist
Labels: iOS

#179 Update Examples to 0.5.0 to dev
  Examples/Cartfile
  Examples/Cartfile.resolved
  Examples/README.md
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/scripts/carthage-input.xcfilelist
Labels: iOS

#125 Fix side effects in RecordingQuota
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Helpers/MemoryByte.swift
  MapboxVision/Helpers/TimeInterval.swift
  MapboxVision/Services/Recording/FileManager.swift
  MapboxVision/Services/Recording/RecordingQuota.swift
  MapboxVision/Services/Sync/RecordSynchronizer.swift
  MapboxVisionTests/Mocks/MockFileManager.swift
  MapboxVisionTests/RecordingQuotaTests.swift
Labels: P2, enhancement, iOS

#184 Add mapbox-accounts dependency
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/scripts/carthage-input.xcfilelist
Labels: P0, iOS

#185 Update changelog
  CHANGELOG.md
Labels: P0, iOS

#188 Update version to 0.6.0
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: P0, iOS

#189 Fix changelog
  CHANGELOG.md
Labels: P0, iOS

#186 Release/0.6.0
  .gitignore
  .swiftformat
  .swiftlint.yml
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/Cartfile
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/scripts/carthage-input.xcfilelist
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Helpers/MemoryByte.swift
  MapboxVision/Helpers/TimeInterval.swift
  MapboxVision/Info.plist
  MapboxVision/Services/Reachability/Reachability.swift
  MapboxVision/Services/Recording/FileManager.swift
  MapboxVision/Services/Recording/RecordingQuota.swift
  MapboxVision/Services/Recording/SessionRecorder.swift
  MapboxVision/Services/Sync/ManagedSynchronizer.swift
  MapboxVision/Services/Sync/RecordSynchronizer.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/SessionRecorderProtocol.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAR/Render/Helpers/ARMath.swift
  MapboxVisionAR/Render/Renderer/ARRenderer.swift
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
  MapboxVisionTests/Info.plist
  MapboxVisionTests/Mocks/MockDataProvider.swift
  MapboxVisionTests/Mocks/MockFileManager.swift
  MapboxVisionTests/Mocks/MockNative.swift
  MapboxVisionTests/Mocks/MockPlatform.swift
  MapboxVisionTests/Mocks/MockSensors.swift
  MapboxVisionTests/Mocks/MockSessionRecorder.swift
  MapboxVisionTests/Mocks/MockSynchronizable.swift
  MapboxVisionTests/Mocks/MockVideoSource.swift
  MapboxVisionTests/RecordingQuotaTests.swift
  MapboxVisionTests/VisionManagerTests.swift
  README.md
Labels: P0, iOS

#187 Release/0.6.0
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: P0, iOS
