Repository mapbox/mapbox-vision-ios, pull requests merged in 2019-05, with the labels that each got.

#95 Update VisionARManager API
  CHANGELOG.md
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
Labels: API Change, P1, iOS

#97 Support updated format of MBVDetection object: `boundingBox` now stores relative coordinates
  CHANGELOG.md
  MapboxVision/View/VisionPresentationViewController.swift
Labels: P0, iOS

#88 Bump sdk dependencies
  Cartfile
  Cartfile.resolved
  MapboxVision.podspec
  MapboxVisionAR.podspec
Labels: P0, iOS

#99 Recording / replaying
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Core/Platform.swift
  MapboxVision/Services/AppDependency.swift
  MapboxVision/Services/Constants.swift
  MapboxVision/Services/DataProvider.swift
  MapboxVision/Services/Recording/RecordCoordinator.swift
  MapboxVision/Services/Recording/RecordingPath.swift
  MapboxVision/Services/Recording/SessionRecorder.swift
  MapboxVision/Services/SessionManager.swift
  MapboxVision/Services/Sync/ManagedSynchronizer.swift
  MapboxVision/Services/Sync/RecordSynchronizer.swift
  MapboxVision/Services/Sync/Synchronizable.swift
  MapboxVision/Services/VideoPlayer.swift
  MapboxVision/Services/VideoSource/ObservableVideoSource.swift
  MapboxVision/Services/VisionSettings.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerDelegate.swift
  MapboxVision/VisionManager/VisionManagerProtocol.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
Labels: API Change, iOS

#100 Update version to 0.4.0
  CHANGELOG.md
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: iOS

#108 Support UK signs
  CHANGELOG.md
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/VisionManager.swift
Labels: P0, bug, iOS

#103 Release/0.4.0 to master
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Core/Platform.swift
  MapboxVision/Helpers/AVCaptureConnection+Orientation.swift
  MapboxVision/Info.plist
  MapboxVision/Services/AppDependency.swift
  MapboxVision/Services/Constants.swift
  MapboxVision/Services/DataProvider.swift
  MapboxVision/Services/LocationManager.swift
  MapboxVision/Services/Reachability/Reachability.swift
  MapboxVision/Services/Recording/ImageRecorder.swift
  MapboxVision/Services/Recording/RecordCoordinator.swift
  MapboxVision/Services/Recording/RecordingPath.swift
  MapboxVision/Services/Recording/SessionRecorder.swift
  MapboxVision/Services/Recording/VideoTrimmer.swift
  MapboxVision/Services/SessionManager.swift
  MapboxVision/Services/Sync/ManagedSynchronizer.swift
  MapboxVision/Services/Sync/RecordSynchronizer.swift
  MapboxVision/Services/Sync/Synchronizable.swift
  MapboxVision/Services/VideoPlayer.swift
  MapboxVision/Services/VideoSource/CameraVideoSource.swift
  MapboxVision/Services/VideoSource/ObservableVideoSource.swift
  MapboxVision/Services/VisionSettings.swift
  MapboxVision/View/DetectionsView.swift
  MapboxVision/View/VideoStreamView.swift
  MapboxVision/View/VisionPresentationViewController.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerDelegate.swift
  MapboxVision/VisionManager/VisionManagerProtocol.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAR/Navigation/ARRoute+DirectionsRoute.swift
  MapboxVisionAR/Render/VisionARViewController.swift
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManager.swift
  MapboxVisionTests/Info.plist
Labels: iOS

#113 Rebase release/0.4.0 to dev
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: iOS

#112 Update version to 0.5.0
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: iOS

#105 Fix some documentation entries
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerDelegate.swift
  MapboxVision/VisionManager/VisionManagerProtocol.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
Labels: iOS

#114 Support setting of attitudeOrient via DeviceMotionData
  CHANGELOG.md
  MapboxVision/Core/Platform.swift
  MapboxVision/Services/MotionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
Labels: iOS
