Repository mapbox/mapbox-vision-ios, pull requests merged in 2019-08, with the labels that each got.

#191 Update version to 0.7.0
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: P0, iOS

#182 Move Reachability logic from MapboxVision
  LICENSE.md
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Services/Reachability/Reachability.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
Labels: API Change, P0, enhancement, iOS

#193 Country based telemetry synchronization
  CHANGELOG.md
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Helpers/Country+SyncRegion.swift
  MapboxVision/Services/Constants.swift
  MapboxVision/Services/EventsManager.swift
  MapboxVision/Services/Network/NetworkClient.swift
  MapboxVision/Services/Recording/DocumentsLocation.swift
  MapboxVision/Services/Recording/FileManager.swift
  MapboxVision/Services/Recording/RecordCoordinator.swift
  MapboxVision/Services/Recording/RecordingPath.swift
  MapboxVision/Services/Recording/SessionRecorder.swift
  MapboxVision/Services/SessionManager.swift
  MapboxVision/Services/Storage/RecordDataSource.swift
  MapboxVision/Services/Sync/ManagedSynchronizer.swift
  MapboxVision/Services/Sync/RecordSynchronizer.swift
  MapboxVision/Services/Sync/Synchronizable.swift
  MapboxVision/Services/SyncRegion.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVisionTests/Helpers/ClosureSyncDelegate.swift
  MapboxVisionTests/Helpers/FileManager+Helpers.swift
  MapboxVisionTests/Mocks/MockFileManager.swift
  MapboxVisionTests/Mocks/MockNetworkClient.swift
  MapboxVisionTests/Mocks/MockRecordDataSource.swift
  MapboxVisionTests/Mocks/MockSessionRecorder.swift
  MapboxVisionTests/Mocks/MockSynchronizable.swift
  MapboxVisionTests/RecordCoordinatorTests.swift
  MapboxVisionTests/RecordSynchronizerTests.swift
  MapboxVisionTests/RecordingPathTests.swift
  MapboxVisionTests/VisionManagerTests.swift
Labels: iOS

#199 Update version to 0.8.0
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: iOS

#200 Update CHANGELOG.md for release 0.7.1
  CHANGELOG.md
Labels: P0, iOS

#201 Update version to 0.7.1.
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: P0, iOS

#202 Release/0.7.1 to master
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionARTests/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: P0, iOS

#205 Release 0.7.1 to dev
  CHANGELOG.md
Labels: P0, iOS

#207 Utilize new ML performance methods
  CHANGELOG.md
  MapboxVision/Core/CoreConfig.swift
  MapboxVision/Services/ModelPerformance.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
Labels: do not merge, iOS
