Repository mapbox/mapbox-vision-ios, pull requests merged in 2019-12, with the labels that each got.

#261 Prevent location updates to crash on stopping VisionManager
  CHANGELOG.md
  MapboxVision/Services/DataProvider.swift
  MapboxVision/Services/LocationManager.swift
Labels: bug, iOS

#262 Fix crash on iterating through camera observers
  CHANGELOG.md
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVision.xcscheme
  MapboxVision/Services/VideoSource/ObservableVideoSource.swift
  MapboxVisionTests/Mocks/MockFrameRecorder.swift
  MapboxVisionTests/ObservableVideoSourceTests.swift
Labels: P0, bug, iOS

#263 Send turnstile event on changing base url
  MapboxVision/Services/EventsManager.swift
Labels: bug, iOS

#264 Adjust api for AR Fence
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAR/VIsionARManager/VisionARManagerDelegate.swift
Labels: API Change, P0, do not merge, iOS
