Repository mapbox/mapbox-vision-ios, pull requests merged in 2019-11, with the labels that each got.

#250 Support Germany in sync region
  MapboxVision/Helpers/Country+SyncRegion.swift
Labels: do not merge, iOS

#248 Update examples
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/VisionExamples/Examples/ExternalCameraViewController.swift
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
Labels: iOS

#254 Update version 0.10.1
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: Release, iOS

#255 Release/0.10.1 to master
  CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Helpers/DeviceChecker.swift
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: Release, iOS

#256 Release/0.10.1 to dev
  .github/stale.yml
  CHANGELOG.md
  MapboxVision/Helpers/DeviceChecker.swift
Labels: Release, iOS

#258 Utilize core-based synchronisation
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/Core/FileSystem.swift
  MapboxVision/Core/Media.swift
  MapboxVision/Core/Platform.swift
  MapboxVision/Core/Telemetry.swift
  MapboxVision/Helpers/Country+SyncRegion.swift
  MapboxVision/Helpers/MemoryByte.swift
  MapboxVision/Helpers/TimeInterval.swift
  MapboxVision/Helpers/URL.swift
  MapboxVision/Helpers/UserDefaults+DefaultValue.swift
  MapboxVision/Services/DataProvider.swift
  MapboxVision/Services/DeviceInfoProvider.swift
  MapboxVision/Services/EventsManager.swift
  MapboxVision/Services/Network/NetworkClient.swift
  MapboxVision/Services/Recording/FileManager.swift
  MapboxVision/Services/Recording/FileRecorder.swift
  MapboxVision/Services/Recording/ImageRecorder.swift
  MapboxVision/Services/Recording/RecordCoordinator.swift
  MapboxVision/Services/Recording/RecordingQuota.swift
  MapboxVision/Services/Recording/SessionRecorder.swift
  MapboxVision/Services/Recording/VideoBuffer.swift
  MapboxVision/Services/Recording/VideoRecorder.swift
  MapboxVision/Services/Recording/VideoTrimmer.swift
  MapboxVision/Services/SessionManager.swift
  MapboxVision/Services/Storage/RecordDataSource.swift
  MapboxVision/Services/Storage/RecordFileType.swift
  MapboxVision/Services/Sync/ManagedSynchronizer.swift
  MapboxVision/Services/Sync/RecordSynchronizer.swift
  MapboxVision/Services/Sync/Synchronizable.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/OperationMode.swift
  MapboxVision/VisionManager/SessionRecorderProtocol.swift
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
  MapboxVisionTests/DeviceCheckerTests.swift
  MapboxVisionTests/DeviceInfoProviderTests.swift
  MapboxVisionTests/Helpers/ClosureSyncDelegate.swift
  MapboxVisionTests/Mocks/MockArchiver.swift
  MapboxVisionTests/Mocks/MockFileManager.swift
  MapboxVisionTests/Mocks/MockFrameRecorder.swift
  MapboxVisionTests/Mocks/MockNative.swift
  MapboxVisionTests/Mocks/MockNetworkClient.swift
  MapboxVisionTests/Mocks/MockPlatform.swift
  MapboxVisionTests/Mocks/MockRecordDataSource.swift
  MapboxVisionTests/Mocks/MockSessionRecorder.swift
  MapboxVisionTests/Mocks/MockSynchronizable.swift
  MapboxVisionTests/Mocks/UIDeviceStubs.swift
  MapboxVisionTests/RecordCoordinatorTests.swift
  MapboxVisionTests/RecordSynchronizerTests.swift
  MapboxVisionTests/RecordingQuotaTests.swift
  MapboxVisionTests/VisionManagerTests.swift
Labels: iOS

#260 Remove location update in background
  CHANGELOG.md
  MapboxVision/Services/LocationManager.swift
Labels: iOS
