Repository mapbox/mapbox-vision-ios, pull requests merged in 2020-03, with the labels that each got.

#278 [Docs] Improve documentation and physical folder structure
  .gitignore
  Docs/CHANGELOG.md
  Docs/CODESTYLE.md
  Docs/CONTRIBUTING.md
  Docs/LICENSE.md
  Examples/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Examples/Resources/Assets.xcassets/Contents.json
  Examples/Resources/Assets.xcassets/alert.imageset/Contents.json
  Examples/Resources/Assets.xcassets/alert.imageset/alert.pdf
  Examples/Resources/Assets.xcassets/close.imageset/Contents.json
  Examples/Resources/Assets.xcassets/close.imageset/close.pdf
  Examples/VisionExamples.xcodeproj/project.pbxproj
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/.jazzy.yaml
  MapboxVision/README.md
  MapboxVision/test_image.png
  MapboxVisionAR.podspec
  MapboxVisionAR/.jazzy.yaml
  MapboxVisionAR/README.md
  MapboxVisionSafety.podspec
  MapboxVisionSafety/.jazzy.yaml
  MapboxVisionSafety/README.md
  MapboxVisionTests/Tests/DeviceCheckerTests.swift
  MapboxVisionTests/Tests/ObservableVideoSourceTests.swift
  MapboxVisionTests/Tests/RecordingPathTests.swift
  MapboxVisionTests/Tests/VisionManagerTests.swift
  README.md
Labels: P0, enhancement, iOS, operation excellence, question

#277 Adopt VideoPlayer to VideoPlayerProtocol
  Docs/CHANGELOG.md
  MapboxVision/Services/Constants.swift
  MapboxVision/Services/VideoPlayer.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
Labels: API Change, DO NOT MERGE, P1, iOS

#281 Update delegate docs
  MapboxVision/VisionManager/VisionManagerDelegate.swift
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManagerDelegate.swift
Labels: documentation, iOS

#283 Getting started code snippet to show basic configuration steps
  Docs/CHANGELOG.md
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Code Snippets/GettingStartedViewController.swift
Labels: P0, documentation, iOS

#284 Merge Getting Started code snippet into master
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Code Snippets/GettingStartedViewController.swift
Labels: P0, documentation, iOS
