Repository mapbox/mapbox-vision-ios, pull requests merged in 2020-01, with the labels that each got.

#266 Fix freeze on init
  MapboxVision/Services/VideoSource/CameraVideoSource.swift
Labels: P0, bug, iOS

#267 Update CHANGELOG.md
  CHANGELOG.md
Labels: P0, Release, iOS

#269 Release/0.11.0 to dev
  CHANGELOG.md
Labels: P0, Release, iOS

#272 Update version 0.12.0
  CHANGELOG.md
  Cartfile.resolved
  Examples/Cartfile
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
Labels: P0, Release, do not merge, iOS
