Repository mapbox/mapbox-vision-ios, pull requests merged in 2020-04, with the labels that each got.

#286 Merge latest master into dev to sync versions
  Examples/VisionExamples/Code Snippets/GettingStartedViewController.swift
Labels: P0, iOS

#287 Update GettingStarted code snippet (merge into master)
  Examples/VisionExamples/Code Snippets/GettingStartedViewController.swift
Labels: P0, documentation, iOS

#279 POI example
  Examples/Resources/Assets.xcassets/car_wash.imageset/Contents.json
  Examples/Resources/Assets.xcassets/car_wash.imageset/car_wash.png
  Examples/Resources/Assets.xcassets/gas_station.imageset/Contents.json
  Examples/Resources/Assets.xcassets/gas_station.imageset/gas_station.png
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Constants.swift
  Examples/VisionExamples/Examples/POIDrawingViewController.swift
  Examples/VisionExamples/Info.plist
Labels: documentation, iOS

#289 AR customization example
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Constants.swift
  Examples/VisionExamples/Examples/ARCustomizationViewController.swift
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
Labels: documentation, iOS

#292 Add comment about the necessity camera parameters
  Examples/VisionExamples/Examples/ExternalCameraViewController.swift
Labels: documentation, iOS

#282 Overspeeding and CollisionDetection example
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Constants.swift
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  Examples/VisionExamples/Examples/SafetyAlertsViewController.swift
Labels: P0, documentation, iOS

#295 Sync dev branch with the latest master
  Examples/Resources/Assets.xcassets/car_wash.imageset/Contents.json
  Examples/Resources/Assets.xcassets/car_wash.imageset/car_wash.png
  Examples/Resources/Assets.xcassets/gas_station.imageset/Contents.json
  Examples/Resources/Assets.xcassets/gas_station.imageset/gas_station.png
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Code Snippets/GettingStartedViewController.swift
  Examples/VisionExamples/Constants.swift
  Examples/VisionExamples/Examples/ARCustomizationViewController.swift
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  Examples/VisionExamples/Examples/ExternalCameraViewController.swift
  Examples/VisionExamples/Examples/OverSpeedingViewController.swift
  Examples/VisionExamples/Examples/POIDrawingViewController.swift
  Examples/VisionExamples/Examples/SafetyAlertsViewController.swift
  Examples/VisionExamples/Info.plist
Labels: P0, iOS

#296 Add update route method
  Docs/CHANGELOG.md
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAR/VIsionARManager/VisionARManagerDelegate.swift
Labels: enhancement, iOS

#298 Update changelog for v0.12.0
  Docs/CHANGELOG.md
Labels: Release, iOS

#301 Update changelog
  Docs/CHANGELOG.md
Labels: Release, iOS

#299 Release/0.12.0
  .gitignore
  Cartfile.resolved
  Docs/CHANGELOG.md
  Docs/CODESTYLE.md
  Docs/CONTRIBUTING.md
  Docs/LICENSE.md
  Examples/Cartfile
  Examples/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Examples/Resources/Assets.xcassets/Contents.json
  Examples/Resources/Assets.xcassets/alert.imageset/Contents.json
  Examples/Resources/Assets.xcassets/alert.imageset/alert.pdf
  Examples/Resources/Assets.xcassets/close.imageset/Contents.json
  Examples/Resources/Assets.xcassets/close.imageset/close.pdf
  Examples/VisionExamples.xcodeproj/project.pbxproj
  Examples/VisionExamples/Examples/ARNavigationViewController.swift
  MapboxVision.podspec
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision/.jazzy.yaml
  MapboxVision/Info.plist
  MapboxVision/README.md
  MapboxVision/Services/Constants.swift
  MapboxVision/Services/ModelPerformance.swift
  MapboxVision/Services/VideoPlayer.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/ManagerDependencies.swift
  MapboxVision/VisionManager/VisionManagerDelegate.swift
  MapboxVision/VisionManager/VisionManagerNativeProtocol.swift
  MapboxVision/VisionManager/VisionManagerProtocol.swift
  MapboxVision/VisionManager/VisionReplayManager.swift
  MapboxVision/test_image.png
  MapboxVisionAR.podspec
  MapboxVisionAR/.jazzy.yaml
  MapboxVisionAR/Info.plist
  MapboxVisionAR/README.md
  MapboxVisionAR/VIsionARManager/VisionARManager.swift
  MapboxVisionAR/VIsionARManager/VisionARManagerDelegate.swift
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/.jazzy.yaml
  MapboxVisionSafety/Info.plist
  MapboxVisionSafety/README.md
  MapboxVisionSafety/VisionSafetyManager/VisionSafetyManagerDelegate.swift
  MapboxVisionTests/Info.plist
  MapboxVisionTests/Mocks/MockNative.swift
  MapboxVisionTests/Tests/DeviceCheckerTests.swift
  MapboxVisionTests/Tests/ObservableVideoSourceTests.swift
  MapboxVisionTests/Tests/RecordingPathTests.swift
  MapboxVisionTests/Tests/VisionManagerTests.swift
  MapboxVisionTests/VisionManagerTests.swift
  README.md
Labels: Release, iOS

#300 Release 0.12.0
  Docs/CHANGELOG.md
Labels: P0, iOS
