Repository mapbox/mapbox-vision-ios, pull requests merged in 2020-05, with the labels that each got.

#304 Update PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE.md
Labels: P1, enhancement, iOS, operation excellence

#305 Update version 0.13.0
  Docs/CHANGELOG.md
  Examples/Cartfile
  MapboxVision.podspec
  MapboxVision/Info.plist
  MapboxVision/Services/ModelPerformance.swift
  MapboxVision/VisionManager/BaseVisionManager.swift
  MapboxVision/VisionManager/VisionManagerProtocol.swift
  MapboxVisionAR.podspec
  MapboxVisionAR/Info.plist
  MapboxVisionAll.podspec
  MapboxVisionSafety.podspec
  MapboxVisionSafety/Info.plist
  MapboxVisionTests/Info.plist
  MapboxVisionTests/Tests/VisionManagerTests.swift
Labels: iOS

#307 Update Xcode project format to Xcode 11.0-compatible.
  Examples/VisionExamples.xcodeproj/project.pbxproj
  MapboxVision.xcodeproj/project.pbxproj
Labels: P1, enhancement, iOS

#309 Fix image format propagation
  Docs/CHANGELOG.md
  MapboxVision/VisionManager/VisionManager.swift
  MapboxVisionTests/Mocks/MockSensors.swift
Labels: iOS

#310 Add Fleet module
  MapboxVision.xcodeproj/project.pbxproj
  MapboxVision.xcodeproj/xcshareddata/xcschemes/MapboxVisionFleet.xcscheme
  MapboxVisionFleet/Info.plist
  MapboxVisionFleet/MapboxVisionFleet.h
  MapboxVisionFleet/VisionFleetManager/VisionFleetManager.swift
  MapboxVisionFleet/VisionFleetManager/VisionFleetManagerDelegate.swift
Labels: iOS
